name = "newsnow-db"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "a82e2f99-2a80-4a90-aa81-ec9bf0190d8e"      # 替换为你创建的数据库 ID
